#!/bin/bash
# filename: sublime_text_3_fcitx
# by: pengzi
# from: http://sublimetext.iaixue.com

sh -c "LD_PRELOAD='/home/yun/bin/sublime_text_3/sublime_text_fcitx.so' '/home/yun/bin/sublime_text_3/sublime_text' --class=sublime-text '$@'"
