#!/bin/bash
#此脚本使用在Android 各项处理上
#制作者：振云
if [[ $1 == "-x" ]]; then
    set -x
    shift
fi
#变量区
# set -xml
filepath=`pwd`
apk=$1
#函数区
GET_APP_NAME(){
	APP_NAME_TMP=$(aapt dump badging $apk | grep application-label:)
	APP_NAME=`echo $APP_NAME_TMP | awk -F "[:']" '{print $3}'`
	echo -n "正在处理: "
	echo -e "\033[36m$APP_NAME\033[0m"
}
GET_APP_PACKAGE_NAME(){
	APP_PACKAGE_NAME_TMP=$(aapt dump badging $apk | grep package:)
	APP_PACKAGE_NAME=`echo $APP_PACKAGE_NAME_TMP | awk -F "[=']" '{print $3}'`
	echo -n "分析包名: "
	echo -e "\033[36m$APP_PACKAGE_NAME\033[0m"
}
GET_APP_MAIN_ACTIVITY(){
	APP_MAIN_ACTIVITY_TMP=$(aapt dump badging $apk | grep "launchable-activity: name=")
	APP_MAIN_ACTIVITY=`echo $APP_MAIN_ACTIVITY_TMP | awk -F "[=']" '{print $3}'`
	echo -n "分析启动类名: "
	echo -e "\033[36m$APP_MAIN_ACTIVITY\033[0m"
}
MAIN(){
	GET_APP_NAME
	GET_APP_PACKAGE_NAME
	GET_APP_MAIN_ACTIVITY
}
HELP(){
	echo -e "s:\tuse:\n \t\tdump -s [apk]\t\t to start this app in your Phone"
    echo -e "i:\tuse:\b \t\tdump -i [apk]\t\t to get apk package name"
}

if [[ ! $1 ]]; then
    HELP 
fi
#选项区
while getopts s:i:c:h opt
do
    case "$opt" in
    s)
	apk=$OPTARG
	MAIN
	echo -n "I will Trying to start "
    echo -ne "\033[36m$APP_NAME\033[0m"
    echo " in your Phone"
	adb shell am start -n ${APP_PACKAGE_NAME}/${APP_MAIN_ACTIVITY}
	break
;;
    i) 
        apk=$OPTARG 
        GET_APP_NAME
        GET_APP_PACKAGE_NAME
         ;;
    c) echo "c options: $OPTARG";;
	h)
        HELP
        ;;
	*) MAIN;;
    esac
done
#流程区
