#!/usr/bin/python
#-*- coding:utf-8 -*-
#此脚本使用在Android 各项处理上
#制作者：振云
import sys
import os
import argparse
#-------------参数区---------------------
op=argparse.ArgumentParser(description='this script is used for extract zip/targz file')
op.add_argument('file',nargs='+',help='first arg is zipfile name ,second arg is target folder')
options=op.parse_args()
file=options.file[0]
print file
try:
    dir=options.file[1]
except Exception, e:
    dir=''.join(file.split('.')[:-1])
    # raise e
print dir
# sys.exit(1)
extract_cmd={'tar.gz'}
#-------------函数区---------------------
#-------------流程区---------------------
if len(options.file)>2:
    op.print_help()
if not os.path.isfile(file):
    print file+' not find!'
    sys.exit(1)
if '.bz2' in file :cmd='bunzip2 '+file
elif '.tar.bz2' in file :cmd='tar xjf '+file
elif '.tar.gz' in file :cmd='tar xzf '+file
elif '.rar' in file :cmd='unrar e '+file
elif '.gz' in file :cmd='gunzip '+file
elif '.tar' in file :cmd='tar xf '+file
elif '.tbz2' in file :cmd='tar xjf '+file
elif '.tgz' in file :cmd='tar xzf '+file
elif '.zip' in file :cmd='unzip '+file+' -d '+dir
elif '.Z' in file :cmd='uncompress '+file
elif '.7z' in file :cmd='7z x '+file
else: print file+' cannot be extracted via extract()'
print cmd
os.system(cmd)
# file=sys.argv[1]
# print len(sys.argv)
# if len(sys.argv)==2:
#     dir=sys.argv[1]
# else:
#     dir=file.split('.')[:-1]
#     print dir

# if not os.path.isfile(file):
#     print file+' not find!'
#     sys.exit(1)