#!/bin/bash
#此脚本用来获取手机型号
#制作者：振云

#变量区
if [[ $1 == "-x" ]]; then
    set -x
    shift
fi
TEST=$1
SDCARD_PATH=/data/media/0
#函数区
GET_DEVICE_SU(){
    ret=$(adb shell ls data)
    if [[ $ret =~ "denied" ]]; then
        ret2=$(adb shell su -c ls data)
        if [[ $ret2 =~ "denied" ]]; then
            echo "The Device Not Root"
             exit
         else
             DEVICE_SU="su -c "
         fi
    else
        DEVICE_SU=""
    fi
}
GET_DEVICE_NAME(){
	DEVICE_NAME_tmp=$(adb shell getprop | grep "ro.product.device")
	DEVICE_NAME=`echo $DEVICE_NAME_tmp |awk -F "[][]" '{print $(NF-1)}'`
}
PRINT_BLOCK_INFO(){
	echo -ne "\033[36m$BLOCK_NAME\033[0m"
	echo -n =
	echo -e "\033[32m$BLOCK_ADDR\033[0m"
}
GET_DEVICE_BLOCK(){
    cs
    modem=$?
#    if [[ $modem == 3 ]]; then
 #       DEVICE_SU=""
  #  fi
	block_tmp=$(adb shell $DEVICE_SU "ls /dev/block/platform")
    
	block_tmp=`echo $block_tmp |awk '{print $1}' | tr -d '\\r'`

	adb shell $DEVICE_SU "ls -al /dev/block/platform/$block_tmp/by-name" > 1.tmp
# cat 1.tmp
	while read block
do
	BLOCK_NAME=`echo $block | awk '{print $(NF-2)}'`
	BLOCK_ADDR=`echo $block | awk '{print $NF}'`
	BLOCK_ADDR=`echo $BLOCK_ADDR | tr -d '\\r'`
	case $BLOCK_NAME in
		"system" | "SYSTEM" | "APP" )
			SYSTEM_BLOCK=$BLOCK_ADDR
			PRINT_BLOCK_INFO
			;;
		"boot" | "BOOT" )
			BOOT_BLOCK=$BLOCK_ADDR
			PRINT_BLOCK_INFO
		;;
		"RECOVERY" | "recovery" )
		RECOVERY_BLOCK=$BLOCK_ADDR
		PRINT_BLOCK_INFO
		;;
		"CACHE" | "cache" )
		CACHE_BLOCK=$BLOCK_ADDR
		PRINT_BLOCK_INFO
		;;
		"data" | "DATA" | "userdata" | "USERDATA" )
		DATA_BLOCK=$BLOCK_ADDR
		PRINT_BLOCK_INFO
		;;
		"misc" | "MISC" )
		MISC_BLOCK=$BLOCK_ADDR
		PRINT_BLOCK_INFO
		;;
		*)
			if [[ $TEST == "-i" ]]; then

				echo "$BLOCK_NAME=$BLOCK_ADDR"
			fi

		;;
	esac
done < 1.tmp
}
#流程区
cs
GET_DEVICE_NAME
GET_DEVICE_SU
case $DEVICE_NAME in
	"m0" )
		GET_DEVICE_BLOCK
		echo -n "Find "
		echo -ne "\033[36mSamsung I9300 \033[0m"
		;;
	"ja3g" )
		GET_DEVICE_BLOCK
		echo -n "Find "
		echo -ne "\033[36mSamsung I9500 \033[0m"
		;;
	"hammerhead")
		GET_DEVICE_BLOCK
		echo -n "Find "
		echo -ne "\033[36mGoogle Nexus \033[0m"
	;;
	"pisces" )
		#DEVICE_SU=""
		SDCARD_PATH=/data/media/0
		GET_DEVICE_BLOCK
		echo -n "Find "
		echo -ne "\033[36mXiaoMi MI3TD \033[0m"
		;;
	"cancro" )
		#DEVICE_SU=""
		GET_DEVICE_BLOCK
		SDCARD_PATH=/data/media/0
		echo -n "Find "
		echo -ne "\033[36mMI3W \033[0m"
		;;
	"lenok" )
		#DEVICE_SU="su -c"
		GET_DEVICE_BLOCK
		echo -n "Find "
		echo -ne "\033[36mLG WATCH R \033[0m"
		;;
	"rolex" | "w1010")
		#DEVICE_SU=""
		GET_DEVICE_BLOCK
		echo -n "Find "
		echo -ne "\033[36mZTE WATCH \033[0m"
	;;
	"OnePlus" | "A0001" )
		#DEVICE_SU="su -c"
		GET_DEVICE_BLOCK
		echo -n "Find "
		echo -ne "\033[36mOnePlus \033[0m"
		;;
	"jflte" | "jfltezm" )
		#DEVICE_SU="su -c"
		GET_DEVICE_BLOCK
		echo -n "Find "
		echo -ne "\033[36mSamsung i9508 \033[0m"
		;;
	"Coolpad8675-A"  )
		#DEVICE_SU=""
		GET_DEVICE_BLOCK
		echo -n "Find "
		echo -ne "\033[36mCoolpad 8675-A \033[0m"
		;;
	"ha3g" )
		#DEVICE_SU="su -c"
		GET_DEVICE_BLOCK
		echo -n "Find "
		echo -ne "\033[36mSamsung N900 \033[0m"
		;;
	"t03gchn" )
		#DEVICE_SU="su -c"
		GET_DEVICE_BLOCK
		echo -n "Find "
		echo -ne "\033[36mSamsung N7100 \033[0m"
		;;
	"G41" )
		#DEVICE_SU="su -c"
		GET_DEVICE_BLOCK
		;;
    "dinara_cg" )
        #DEVICE_SU="su -c"
        GET_DEVICE_BLOCK
        echo -n "Find "
        echo -e "\033[36mMoto XT928 \033[0m"
        ;;
    "watch" )
        #DEVICE_SU=""
        GET_DEVICE_BLOCK
        echo -n "Find "
        echo -e "\033[36mIngenic Watch \033[0m"
        ;;
	* )
		#DEVICE_SU="su -c"
		GET_DEVICE_BLOCK
		echo -n "Find "
		echo -ne "\033[33mUnknow Device .....\033[0m"
		;;
esac
rm 1.tmp
echo -n "device : "
echo -e "\033[32m$DEVICE_NAME\033[0m"
