#!/usr/bin/python
#-*- coding:utf-8 -*-
#此脚本用来登录常用的服务器
import commands
import sys
import os
from common import bcolors
#-------------参数区---------------------
home=os.environ['HOME']
config_file=os.path.join(home,'.serve')
number=1
addr=[]
port=[]
name=[]
selected=False
#-------------函数区---------------------
#-------------流程区---------------------
while not selected:
    for line in open(config_file):
        if ":" in line:
            addr.append(line.split(":")[2].strip())
            port.append(line.split(":")[1].strip())
            name.append(line.split(":")[0].strip())
            print str(number)+".\t"+bcolors.WARNING_ORANGE+name[number-1]+bcolors.ENDC+":\tport="+bcolors.LIGHT_BLUE+port[number-1]+bcolors.ENDC+ "\taddr="+bcolors.OKGREEN+addr[number-1]+bcolors.ENDC
        number+=1
    try:
        choose=int(raw_input('please input you chose:  '))
    except Exception, e:
        print "input text "+bcolors.FAIL+"error! "+bcolors.ENDC
        print
        number=1
        continue
    if choose < number:
        selected=True
    else:
        print "input text "+bcolors.FAIL+"error! "+bcolors.ENDC
        print
        number=1
print "addr="+addr[choose-1]
print "port="+port[choose-1]
server_port=port[choose-1]
server_addr=addr[choose-1]
cmd='ssh -p '+server_port+' '+server_addr
print cmd
os.system('clear')
os.system(cmd)
