#!/usr/bin/python
#-*- coding:utf-8 -*-
#此脚本用来登录常用的服务器
import commands
import sys
import os
from common import bcolors
#-------------参数区---------------------
home=os.environ['HOME']
config_file=os.path.join(home,'.serve')
number=1
addr=[]
port=[]
name=[]
selected=False
new_serve=False
file_exist=False
#-------------函数区---------------------
def check_env():
    global file_exist
    if os.path.isfile(config_file):
        file_exist=True
    else:
        print "开始创建新的服务器配置:\t"+ config_file
        fo=open(config_file,"a+")
        fo.close()
def login_serve():
    cmd='ssh -p '+server_port+' '+server_addr
    os.system('clear')
    ret=os.system(cmd)
    return ret
#-------------流程区---------------------
check_env()
while not selected:
    for line in open(config_file):
        if ":" in line:
            addr.append(line.split(":")[2].strip())
            port.append(line.split(":")[1].strip())
            name.append(line.split(":")[0].strip())
            print str(number)+".\t"+bcolors.WARNING_ORANGE+name[number-1]+bcolors.ENDC+":\tport="+bcolors.LIGHT_BLUE+port[number-1]+bcolors.ENDC+ "\taddr="+bcolors.OKGREEN+addr[number-1]+bcolors.ENDC
        number+=1
    print str(number)+".\t"+bcolors.OKGREEN+"new"+bcolors.ENDC
    try:
        choose=int(raw_input('please input you chose:  '))
    except Exception, e:
        print "input text "+bcolors.FAIL+"error! "+bcolors.ENDC
        print
        number=1
        continue
    if choose < number:
        selected=True
    elif choose == number:
        new_serve=True
        selected=True
    else:
        print "input text "+bcolors.FAIL+"error! "+bcolors.ENDC
        print
        number=1
if new_serve:
    print "a new serve"
    server_name=raw_input("请输入服务器名称：\t")
    server_port=raw_input("请输入服务器端口号：\t")
    user=raw_input("请输入远程用户名：\t")
    addr=raw_input("请输入服务器ip地址：\t")
    server_addr=user+'@'+addr
    print "new.\t"+bcolors.WARNING_ORANGE+server_name+bcolors.ENDC+":\tport="+bcolors.LIGHT_BLUE+server_port+bcolors.ENDC+ "\taddr="+bcolors.OKGREEN+server_addr+bcolors.ENDC
    ret=login_serve()
    if ret==0:
        fo=open(config_file,"a+")
        # print file_exist
        if file_exist:
            fo.write('\n')
        fo.write(server_name+':'+server_port+':'+user+'@'+addr)
        fo.close()
    else:
        print str(ret)
else:
    print "addr="+addr[choose-1]
    print "port="+port[choose-1]
    server_port=port[choose-1]
    server_addr=addr[choose-1]
    login_serve()
