#!/usr/bin/python
#-*- coding:utf-8 -*-
#此脚本使用在Android 各项处理上
#制作者：振云
import sys
import commands
import os
from common import bcolors
import argparse
#-------------参数区---------------------
option=argparse.ArgumentParser(description='this Python Script is used for make samgung odin package')
option.add_argument('files',type=str,help='input file to make odin tars')
options=option.parse_args()
#-------------函数区---------------------
#-------------流程区---------------------

#变量区
target=options.files
print target
cmd='tar -cf '+target+'.tar '+target
print cmd
(status,output)=commands.getstatusoutput(cmd)
if status!=0:
	print 'make odin package '+bcolors.FAIL+'Failed:'+bcolors.ENDC
	print output
	os.remove(target+'.tar')
	sys.exit(1)
cmd='md5sum -t '+target+'.tar >> '+target+'.tar'
(status,output)=commands.getstatusoutput(cmd)
if status!=0:
	print 'make odin package '+bcolors.FAIL+'Failed:'+bcolors.ENDC
	print output
	os.remove(target+'.tar')
	sys.exit(1)
print 'make odin package '+bcolors.OKGREEN+'Succeeded!'+bcolors.ENDC
