#!/usr/bin/python
#-*- coding:utf-8 -*-
#此脚本用来打印证书信息，支持apk。RSA，X509.pem文件

import os
import sys
import commands
import argparse
import shutil
#-------------参数区---------------------
LOCAL_PATH=os.environ['PWD']
apk_rsa_path='/tmp/META-INF/*.RSA'
op=argparse.ArgumentParser(description="此脚本用来打印证书信息，支持apk/RSA/X509.pem文件")
op.add_argument('file',type=str,help="输入apk,rsa,x509文件路径")
options=op.parse_args()
#-------------函数区---------------------
def print_apk_cert():
    if os.path.isdir('/tmp/META-INF'):
        shutil.rmtree('/tmp/META-INF')
    cmd='unzip -d /tmp/ '+TARGET+' "META-INF/*.RSA"'
    (status,output)=commands.getstatusoutput(cmd)
    print_cert_info(apk_rsa_path)
def print_cert_info(cert):
    cmd='keytool -printcert -file '+cert
    (status,output)=commands.getstatusoutput(cmd)
    print output
def print_keystore_info(keystore):
    cmd='keytool -list -v -keystore %s' % keystore
    os.system(cmd)
#-------------流程区---------------------
TARGET=options.file
if '.apk' in TARGET or '.zip' in TARGET:
    print_apk_cert()
elif 'x509.pem' in TARGET or 'RSA' in TARGET:
    print_cert_info(TARGET)
elif 'keystore' in TARGET:
    print_keystore_info(TARGET)
else:
    print "不支持这种格式的文件！"
    sys.exit(1)