#!/usr/bin/python
#-*- coding:utf-8 -*-
#此脚本使用在Android 各项处理上
#制作者：振云
import sys
import commands
from common import bcolors

#-------------参数区---------------------
BRANCH='master'
#-------------函数区---------------------
def get_branch():
	cmd="""git branch | grep '*'| awk '{print $NF}'|tr -d '\\r'"""
	# print cmd
	output=commands.getoutput(cmd)
	if "Not a git repository" in output:
		print output
		sys.exit(1)
	return output
def get_branch_remote():
    cmd="git status"
    (status,output)=commands.getstatusoutput(cmd)
    str=output.split('\n')
    # print str
    # print len(str)
    for line in str:
        if "Your branch" in line:
            # print line
            branch_info=line.split("'")[1]
            remote=branch_info.split('/')[0]
            branch=branch_info.split('/')[1]
            # print remote,branch
            return remote,branch
    print "get branch error ...."
    print output
    sys.exit(1)

#-------------流程区---------------------
# get_branch_remote()
# sys.exit(0)
remote,branch=get_branch_remote()
print 'push to the remote '+bcolors.OKGREEN+remote+' '+bcolors.OKBLUE,branch,bcolors.ENDC
cmd='git push -u '+remote+' '+branch
print cmd
output=commands.getoutput(cmd)
print output
