#!/usr/bin/python
#-*- coding:utf-8 -*-
#此脚本使用在Android 各项处理上
#制作者：振云
import sys
import commands
from common import bcolors

#-------------参数区---------------------
BRANCH='master'
#-------------函数区---------------------
def get_branch():
	cmd="""git branch | grep '*'| awk '{print $NF}'|tr -d '\\r'"""
	# print cmd
	output=commands.getoutput(cmd)
	if "Not a git repository" in output:
		print output
		sys.exit(1)
	return output

#-------------流程区---------------------
branch=get_branch()
print 'push to the remote origin '+bcolors.OKBLUE,branch,bcolors.ENDC
cmd='git push -u origin '+branch
# print cmd
output=commands.getoutput(cmd)
print output
