#!/bin/bash
#此脚本使用在Android 各项处理上
#制作者：振云

#变量区
if [[ $1 == "-x" ]]; then
    set -x
    shift
fi

#函数区

LINK_BASHRC(){
	# rm -rf $HOME/.vim/
	# ln -s $HOME/bin/vim $HOME/.vim
	rm $HOME/.bash_profile
    rm $HOME/.vimrc
    rm -r $HOME/.vim
	ln -s $HOME/bin/config/bashrc  $HOME/.bash_profile
	ln -s $HOME/bin/config/vimrc $HOME/.vimrc
    ln -s $HOME/bin/config/vim $HOME/.vim
}

SVN_DIFF(){
	if [ ! -f "/usr/bin/bcdiff.sh" ]; then
		sudo ln -s $HOME/bin/config/bcdiff.sh /usr/bin/bcdiff.sh
		rm ~/.subversion/config
		ln -s  $HOME/bin/config/svn_config $HOME/.subversion/config
	fi
}
#流程区
LINK_BASHRC
SVN_DIFF
chmod 777 ~/bin
if [[ ! -f "$HOME/.git-credentials" ]]; then
    touch $HOME/.git-credentials
    git config --global credential.helper store
    echo "please fill your github/git.code username & password in ~/.git-credentials"
    echo -e "eg:\n\t https://username:password@github.com"
fi
echo -e "\033[32mDone!\033[0m"
