#!/bin/bash
#此脚本使用在Android 各项处理上
#制作者：振云
PATH=/bin:/sbin:/usr/bin:usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin:$TOOLPATH
export PATH

#变量区
set -x
#选项区
while getopts :a:b:c:h opt
do
    case "" in
    a) echo "a options";;
    b) echo "b options and the value is  " ;;
    c) echo "c options";;
	h) echo -e "a:\ta options\nb:\tb options\nc:\tc options";;
	*) echo -e "unknow options: \ninput -h to get help doc";;
    esac
done
#函数区
CP_51_ANDROD(){
	if [[ -f "/etc/udev/rules.d/51-android.rules" ]]; then
		echo -n "the Android rules "
		echo -ne "\033[32m51-android.rules\033[0m"
		echo " has exist"
		echo -ne "\033[33mSkipping \033[0m"
		echo "copy 51-android.rules...."
	else
		sudo cp 51-android.rules /etc/udev/rules.d/
	fi
}
LINK_BASHRC(){
	rm -rf $HOME/.vim
	ln -s $HOME/bin/vim $HOME/.vim
	rm $HOME/.bashrc
    rm $HOME/.vimrc
    rm $HOME/.git-completion.bash
	ln -s $HOME/bin/bashrc  $HOME/.bashrc
    ln -s $HOME/bin/vimrc $HOME/.vimrc
    ln -s $HOME/bin/git-completion.bash $HOME/.git-completion.bash
    rm ~/.gconf/apps/gnome-terminal/profiles/Default/%gconf.xml
	ln -s $HOME/bin/config/bash_%gconf.xml $HOME/.gconf/apps/gnome-terminal/profiles/Default/%gconf.xml
}
INSTALL_SOFTWARE(){
		sudo apt-get install bison build-essential curl flex git gnupg gperf libesd0-dev libncurses5-dev libsdl1.2-dev libwxgtk2.8-dev libxml2 libxml2-utils lzop openjdk-6-jdk openjdk-6-jre pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev g++-multilib gcc-multilib lib32ncurses5-dev lib32readline-gplv2-dev lib32z1-dev git-cola gitk wget trimage openjdk-7-jdk vim vim-doc guake tree gnuplot-qt exuberant-ctags cscope subversion imagemagick exiftool expect python3-markdown python3-docutils vim-youcompleteme
}
INSTALL_SUBLIME(){
	cd sublime_text_3
	sudo ./firstrun.sh
	cd -
}
SVN_DIFF(){
    sudo ln -s $HOME/bin/bcdiff.sh /usr/bin/bcdiff.sh
    rm ~/.subversion/config
    ln -s  $HOME/bin/config/svn_config $HOME/.subversion/config
}
#流程区
CP_51_ANDROD
LINK_BASHRC
INSTALL_SOFTWARE
INSTALL_SUBLIME
SVN_DIFF
chmod 777 ~/bin -R
if [[ ! -f ".git-credentials" ]]; then
    touch $HOME/.git-credentials
    echo "please fill your github/git.code username & password in ~/.git-credentials"
    echo -e "eg:\n\t https://username:password@github.com"
fi
echo -e "\033[32m\nDone\n\033[0m"
