#!/bin/bash
#此脚本用来测试OTA使用
#制作者：陈云

#变量区
FILE=$1
COMMAND="/cache/recovery/command"
TMP_COMMAND="/tmp/command"
PACKAGE_PATH1=/sdcard
PACKAGE_PATH2=/sdcard/0
FILE_BASE=`basename $FILE`
set -x
#函数区
WRITE_COMMAND(){
	echo "最后准备中,即将开始刷机"
    echo "--update_package=$PACKAGE_PATH2/$FILE_BASE" >>$TMP_COMMAND
    cat $TMP_COMMAND
    p $TMP_COMMAND $PACKAGE_PATH/
    if [[ $? == 1 ]]; then
    		echo "自动刷机脚本传输失败,重新传输"
    		CLEAN
		WRITE_COMMAND
	fi
   cp_result=$(adb shell "cp $PACKAGE_PATH/command cache/recovery/")

   cp_result_tmp=`echo $cp_result | awk '{print $(NF-1)}'`
   cp_result_tmp=`echo $cp_result_tmp`
   if [[ "$cp_result_tmp" == "Permission" ]]; then
   	echo $cp_result
   	cp_result=$(adb shell su -c "cp $PACKAGE_PATH/command cache/recovery/")
   	echo $cp_result
   fi
}
CLEAN(){
    rm $TMP_COMMAND
}
GO_RECOVERY(){
    cs
    status=$?
    case $status in
	2 )
	PACKAGE_PATH=$PACKAGE_PATH1
       	echo "正在将刷机包传输到内存卡......"
	p $FILE $PACKAGE_PATH/
	if [[ $? == 1 ]]; then
		echo -e "\033[31m传输失败,重新传送\033[0m"
		GO_RECOVERY
		clear
	fi
		;;
	3)
	echo "正在将刷机包传输到内存卡......"
	PACKAGE_PATH=$PACKAGE_PATH2
	p $FILE $PACKAGE_PATH/
	if [[ $? == 1 ]]; then
		echo -e "\033[31m传输失败,重新传送\033[0m"
		GO_RECOVERY
		clear
	fi
		;;
	4)
	echo " 退出Fastboot模式....."
	re
        GO_RECOVERY
        ;;
esac
}
#主体流程区
CLEAN
GO_RECOVERY
WRITE_COMMAND
CLEAN
reco
echo "自动刷机即将开始"
m