#!/bin/bash
#此脚本使用在Android 各项处理上
#制作者：振云

#变量区
if [[ $1 == "-x" ]]; then
	set -x
	shift
fi
FILE=$1
COMMAND="/cache/recovery/command"
TMP_COMMAND="/tmp/command"
FILE_BASE=`basename $FILE`
. getPhoneName
#函数区
CLEAN(){
	rm $TMP_COMMAND
}
PUSH_FILE(){
	echo "正在将刷机包传输到内存卡......"
	p $FILE $SDCARD_PATH2
	if [[ $? == 1 ]]; then
		echo -e "\033[31m传输失败,重新传送\033[0m"
		sleep 2
		PUSH_FILE
	fi
}
GET_CURRENT_STATUS(){
	cs
	status=$?
	case $status in
		2 )
			m
			SDCARD_PATH2=sdcard
			PUSH_FILE
			;;
		3 )
			ｍ
			SDCARD_PATH2=$SDCARD_PATH
			PUSH_FILE
		;;
		4)
			echo " 退出Fastboot模式....."
			re
			GET_CURRENT_STATUS
		;;
esac
}
WRITE_COMMAND(){
	echo "最后准备中,即将开始刷机"
	echo "--update_package=$SDCARD_PATH/$FILE_BASE" >$TMP_COMMAND
	cat $TMP_COMMAND
}
PUSH_COMMAND(){
	p $TMP_COMMAND $SDCARD_PATH2
	if [[ $? == 1 ]]; then
		echo "自动刷机脚本传输失败,重新传输"
		CLEAN
		sleep 2
		PUSH_COMMAND
    fi 
    m
	cp_result=$(adb shell "cp $SDCARD_PATH2/command cache/recovery/")
    echo $cp_result
	if [[ $cp_result != "" ]]; then
		cp_result_tmp=`echo $cp_result | awk '{print $(NF-1)}'`
		cp_result_tmp=`echo $cp_result_tmp`
		if [[ "$cp_result_tmp" == "Permission" ]]; then
		echo $cp_result
		cp_result=$(adb shell su -c "cp $SDCARD_PATH/command cache/recovery/")
	 	echo $cp_result
	fi
	fi
}
#选项区

#流程区
CLEAN
GET_CURRENT_STATUS
WRITE_COMMAND
PUSH_COMMAND
CLEAN
reco
echo "自动刷机即将开始"
echo -e "\033[32mDone!\033[0m"
